server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:blog
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
