name: Push on main

on:
  push:
    branches:
      - main

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build backend application
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build -i
      - name: Build backend docker image
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: docker -i
      - name: Build react-ui application docker image
        run: |
          cd gwi-blog-react-ui
          docker build -t guizer/gwi-blog-react-ui:1.0-SNAPSHOT .
      - name: Push docker images
        run: |
          echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker image tag gwi-blog/gwi-blog-backend:1.0-SNAPSHOT guizer/gwi-blog-backend:1.0-SNAPSHOT
          docker image push guizer/gwi-blog-backend:1.0-SNAPSHOT
          docker image push guizer/gwi-blog-react-ui:1.0-SNAPSHOT
